name: CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        nvim: [v0.8.3, stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker-based tests (${{ matrix.nvim }})
        env:
          DOCKER_PLATFORM: linux/amd64
          NVIM_VERSION: ${{ matrix.nvim }}
        run: make d-test

  gate:
    name: gate
    runs-on: ubuntu-24.04
    needs: [test]  # only runs if all matrix jobs passed
    steps:
      - run: echo "all checks passed"